[theme]
base                     = "dark"
primaryColor             = "#FC4C02"
backgroundColor          = "#0F0F1E"
secondaryBackgroundColor = "#16162A"
textColor                = "#EEEEFF"
font                     = "sans serif"

[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
